version: '2'
services:
  test:
    build: .
    environment:
      DEBUG: "true"
      SNAPSHOT_METHOD: local
      SNAPSHOT_COMPRESSION: zip
      SNAPSHOT_LOCATION: /s3
      SNAPSHOT_S3_DESTINATION: /root
      SNAPSHOT_INTERVAL: 15