version: '2'
services:
  test:
    build: .
    volumes:
      - "~/.aws:/root/.aws"
    environment:
      DEBUG: "true"
      SNAPSHOT_METHOD: s3
      SNAPSHOT_COMPRESSION: zip
      SNAPSHOT_LOCATION: /s3
      SNAPSHOT_DESTINATION: s3://robpc-minecraft/backup
      SNAPSHOT_INTERVAL: 15
      SNAPSHOT_INCLUDE_DIR: "FALSE"
      SNAPSHOT_START_DELAY: 0